project:
  type: website

website:
  title: "Emiliano Mora-Carrera, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: github.qmd
        text: GitHub
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contacts

format:
  html:
    page-layout: full
    theme:
      light: yeti
    toc: true
    css: styles.css
execute:
  freeze: auto