# Curriculum Vitae

## Profesional experience

### Postdoctoral Researcher (2023 to present)

University of Zurich

Zurich, Switzerland

### Laboratory Research Assitant (2016 to 2018)

National Autonomous University of Mexico

Mexico City, Mexico


## Education

### PhD Evolutionary Biology (2018 to 2023)

University of Zurich

Zurich, Switzerland

### MSc Biological Sciences (2014 to 2016)

National Autonomous University of Mexico (UNAM)

Mexico City, Mexico

### BSc Biology (2009 to 2014)

University of Sonora

Hermosillo, Sonora, Mexico


## Teaching experience

* Main teacher – *Pollination Ecology* (Fall 2018). National Autonomous University of Mexico.
* Teaching assistant – *Molecular Evolution and Phylogenetics* (Fall 2018 and Fall 2019). University of Zurich.
* Teaching assistant – *Evolution* (Fall 2019 and Fall 2020). University of Zurich.
* Teaching assistant – *Introduction to Ecological Genomics and Molecular Adaptation* (Fall 2020). University of Zurich.
* Teaching assistant – *Genome Evolution and Diversity* (Fall 2020, Fall 2021, Spring 2022, Spring 2024 and Spring 2025). University of Zurich.


## Awards & Grants

* CUMex grant for International Exchange in Mount Royal University, Alberta, Canada (Fall 2012) (54,000 MXN)
* PAEP UNAM grant to attend the Evolution Meeting 2016 Austin, TX (15,000 MXN)
* PAEP UNAM grant for early graduation (20,000 MXN)
* Swiss Government Excellence Scholarship for Foreign Students (2018-2021) (70,000 CHF)
* GRC Travel Grant 2018 (1,300 CHF) 
* GRC Travel Grant 2019 (2,200 CHF)
* Forschungskredit Candoc UZH 2021 (43,160 CHF)


## Scientific outreach

* Decider of the XII Contest “Leamos la Ciencia para Todos” Fondo de Cultura Económica (Summer 2012).
* Mora-Carrera, E. (2018) México y sus polinizadores: Crónica de una crisis anunciada. Published in ‘Oikos=’ (UNAM Magazine for Science Outreach).
* Co-host of the Botanical Club UNISON (2014-2015).
* Science Information Day at UZH Faculty of Science (March 2019).
* Co-organizer of the UZH EvoBio PhD retreat (June 2019).
* Organizer of the PhD Symposium from the Institute of Systematics and Evolutionary Botany University of Zurich (September 2021).
* Event Manager. Pint of Science (May 2023)


## Certificates

A downloadable PDF version of all certificates can be found [here](files/certificate_concatenated.pdf).

## CV

A downloadable PDF version of my CV will be available [here](files/CV_EmilianoMora_long.pdf).